# Generated by Django 4.0.6 on 2022-07-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('extension', models.CharField(choices=[('cpp', 'C++'), ('c', 'C'), ('java', 'Java'), ('py', 'Python')], default='cpp', max_length=4)),
                ('code', models.TextField()),
            ],
        ),
    ]
