# Generated by Django 3.2.15 on 2022-08-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('fileextension', models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('c', 'C'), ('js', 'Node.JS')], max_length=4)),
                ('codefile', models.CharField(max_length=1048576)),
                ('name', models.CharField(max_length=64, null=True)),
                ('last_edit', models.DateField(auto_now=True)),
            ],
        ),
    ]
