# Generated by Django 3.2.15 on 2022-08-04 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileextension', models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('c', 'C'), ('js', 'Node.JS')], max_length=4)),
                ('codefile', models.CharField(max_length=1048576)),
            ],
        ),
    ]
