# Generated by Django 3.2.15 on 2022-08-10 21:18

import Home.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='user',
        ),
        migrations.AddField(
            model_name='code',
            name='owner',
            field=Home.fields.OwnerField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='code',
            name='codefile',
            field=models.TextField(max_length=1048576),
        ),
        migrations.AlterField(
            model_name='code',
            name='fileextension',
            field=models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('c', 'C'), ('js', 'Node.JS')], max_length=4, verbose_name='Language'),
        ),
    ]
