# Generated by Django 3.2.15 on 2022-08-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='NewCode',
        ),
    ]
